---
title: "BM330 Classic Papers in Microbiology Journal Club"
author: "Morgan Feeney"
date: "2022 Presentation"
output: 
  bookdown::html_document2:
    toc: true
    toc_float:
      toc_collapsed: false
    number_sections: true
    css: "css/rmd_style.css"
    theme: lumen    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<div id="summary">
- A summary of some of the issues that you should consider when planning your journal club presentation: content, methods, data presentation, aesthetics, delivering your presentation.
- Some of the common mistakes we see in journal club presentations, and how to avoid them
- Suggested additional reading on how to give good presentations
</div>

# Introduction

This is a companion guide to the BM330 workshop A (Classic Paper Journal Club). We have collated some information and helpful tips that will assist you in preparing your journal club presentation. However, reading these tips is not a substitute for attending workshop A - where we will discuss the classic paper journal club in more detail. 

# The Anatomy of a Journal Club Presentation

Every talk is different, and all of the classic papers we study in BM330 are different - but every journal club talk should contain the following elements in some form: 
- An explanation of the problem that the authors were trying to solve, and the historical context they were working in (what was known before the authors began this study, and what they were trying to achieve)
- A description of the work that was done (this should include materials & methods/experimental design, results and conclusions)
- An explanation of the significance of the work (what other work was made possible because of this paper? how did it change our understanding of microbiology?)
- Critical analysis of the paper (including, but not limited to: limitations of the experimental design, controls, alternative experimental approaches...)

Boiled down to the essentials, your presentation should inform your audience of why your assigned paper is important; describe the aims/hypothesis of your work, what experiments were done and how, and the overall conclusions/"take-home messages"; and help your audience understand the historical context and significance of the paper.  

## Content

- You should present the key experiment(s)^[You do not need to present every single experiment described in the paper; in fact, you probably should not try to do so. Decide which experiments are **essential** for conveying the take-home message.]from your paper. 
- For every experiment, you should present (<b>in this order</b>):
  1. what it is that the authors were trying to do (the <b>aim</b> of the experiment)
  2. how they did it (the <b>method</b>)
  3. what they found (the <b>result(s)</b> of the experiment) 
  4. and what it means (the <b>significance</b> of these results to the field)

[Read more about the content of a journal club presentation](./presentations-content.html)

### Methods

- You should give enough information for the reader to understand how the experiments were done
  - Give any key parameters for the methods done, but you do not need to be as detailed as a paper/thesis: your audience should understand how the experiments were done, they do not need to reproduce them.
- A good presentation often uses a figure/flow diagram to illustrate the methods, explaining key steps in the process (see the [section on figures](./presentations-figures.html) for an example)


### Data (Figures and Tables, mostly)

- Any data you present in your talk should help convince the reader of your take-home message.
- You will very often want to reproduce the relevant figure from the paper itself (and this is absolutely fine!), but in some cases it may be helpful to modify the figure for your presentation (e.g., relabel the figure to make it easier for your audience to read).

[Read more about presenting data in a journal club presentation](./presentations-figures.html)

## Aesthetics

- Your slides should be visually appealing to the audience and should be easy for them to read and interpret.
- Be wary of using any design elements that distract or detract from the main take-home message of the presentation.
- Be mindful in your use of colour, font, and slide background - make sure that your design choices enhance your presentation.

[Read more about the aesthetics of a journal club presentation](./presentations-aesthetics.html)

# Preparing slides and delivering a talk

- Probably the most commonly used software for preparing slides is PowerPoint, but alternatives exist (Keynote, Canva, Prezi) - you may use any software you like to prepare your talk.^[If you are using one of the less common software, please make sure to communicate with your workshop leader in advance of your session about the logistics of your presentation.]
- Your slides should support your presentation. They serve two purposes: 1) to prompt you and help you remember what you want to say, and 2) to help your audience understand your talk. 

[Read more about how to make slides for a journal club presentation](./slide-preparation.html)

[Read more about how to deliver a journal club presentation](./presentation.html)
  

# Common mistakes we often see in students' journal club presentations (and how to avoid them)

*Too much content covered*

- Do not try to explain every single experiment presented in the paper - instead, focus on conveying the [take-home message](./presentations-content.html) of the paper.


*Separate methods sections*

- Sometimes presenters try to cover all of the methods from a paper in one slide - it is better to weave the methods into the story of the paper, explaining each method just before the experiment that used it. Otherwise your audience will not remember the method by the time you describe that experiment.


*Too much text on slides/slides too busy*

- Be ruthless in eliminating content from slides: if you don't mention something when practicing your presentation, remove it from the slides! Also consider using animations to bring items/text onto the slides gradually - that way your audience will be listening to you, instead of reading a whole block of text all presented at once.


*Uninformative slide titles*

- Think carefully about what the take-home message of each slide is. The slide title should not be what the purpose of the slide is (i.e., "Introduction") - it should be what you want your audience to remember from that slide (i.e., "Initiation of DNA Replication").


*Critical analysis missing/lacking*

- Critical analysis here is not an analysis of the paper's structure, how well written it is, or how much you liked reading it. Critical analysis should be a rigorous analysis of the experiments described in the paper. Ask questions like: were the correct controls performed? are there any alternative interpretations of the data? what other methods could the authors have used to address their question?


*Historical background/significance lacking*

- Make sure you read the paper carefully, but also read other papers that cite your paper (to measure its impact) or papers that were published before your paper (to understand what was the state of the field at the time).


*No clear aim/hypothesis*

- The aim and/or hypothesis may not be explicitly stated in the paper. Read the paper carefully to understand what it was the authors were trying to achieve, and state their aims/hypothesis in your own words. Highlight these during your presentation so that your audience understands why the authors had these particular aims/hypothesis.

*Timing issues (under or over time)*

- Practice, practice, practice! You will often find that your final presentation is a little faster than your practices (you will likely speak a bit faster than usual due to nerves: this is common, and it decreases with practice.) Practice in front of a mirror or your pet, your friends/family/colleagues; use a timer and practice until you can give your presentation in the allocated time. Have a very good idea of what you want to say for each slide so that you don't "ummm" and "ah" when you present.




# FAQ
- There are no FAQ yet as this is a brand new page!
- Please e-mail Dr. Feeney or Prof. Hoskisson with any questions or with any suggestions for how we can improve these pages.



# Additional reading

- Naegle KM (2021) Ten simple rules for effective presentation slides. PLOS Computational Biology 17(12): e1009554. https://doi.org/10.1371/journal.pcbi.1009554
- Carey MA, Steiner KL, Petri WA Jr (2020) Ten simple rules for reading a scientific paper. PLOS Computational Biology 16(7): e1008032. https://doi.org/10.1371/journal.pcbi.1008032
- [Data visualization: A view of every Points of View column](https://protocolsmethods.springernature.com/posts/43650-data-visualization-a-view-of-every-points-of-view-column) - great tips on data visualization (organised by topic)
- Karen J. Murchie and Dylan Diomede. Fundamentals of graphic design—essential tools for effective visual science communication. FACETS. 5(1): 409-422. https://doi.org/10.1139/facets-2018-0049