---
title: "Classic Papers Journal Club: Presentation Content"
author: "Morgan Feeney"
date: "2021 Presentation"
output: 
  bookdown::html_document2:
    toc: true
    toc_float:
      toc_collapsed: false
    number_sections: true
    css: "css/rmd_style.css"
    theme: lumen    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<div id="summary">
- A journal club presentation helps to communicate the results of a particular study to an audience 
  - Be sure to identify the take-home message of the paper, and convey this clearly in your presentation
  - Slides should help the presenter communicate (serve as a visual aid/memory prompt), but should also be able to stand alone (communicate the work done without the author present to explain it)
- For each experiment, you should explain the aim, method, result(s), and significance
</div>



# Identify the "Take-Home Message"

Summarize in 1-3 sentences what it is that you want your audience to remember after hearing your talk.
- Why your assigned paper is important, how it addressed a gap in the literature (discovered something that wasn't known before), how it has revolutionized the field of microbiology or biology as a whole
- What it is specifically was found in the paper, the main and most important conclusion you can draw from the results

Everything that you choose to include in your talk should support this message. 

<div id="warning">
Identifying the "Take-Home Message" is crucial to giving a good journal club presentation, but it is by no means an easy task!

You will need to read the paper thoroughly (probably several times!), think about it, read other papers in the area and/or papers that cite your assigned paper, and critically evaluate your paper based on this evidence. 
</div>


<div id="goofus-gallant">
<div id="goofus">
*Bad examples of "take-home messages"*
  
- Antibiotics are important
  - Too vague (which antibiotics? important for what?); does not give any precise idea of what this work added to the field
- RpoS is conserved in bacteria
  - Does not explain what RpoS is or why it is important; does not give any precise idea of what this work added to the field 
- The OxyR regulon includes *hemH, ahpC, dsbG, fur, dps, grxA, hcp,* the *suf* and *znu* genes, *trxC*, and *gor*. *gor* encodes glutathione reductase and is an essential gene in *Escherichia coli*. We found that some bacteria do not have the *gor* gene.
  - contains a lot of information that is not germane to the main point (long list of genes - not clear what any of them do or why they are important); gives some idea of what your work adds to the field, but a bit vague (which bacteria lack *gor*?)
</div>

<div id="gallant">
*Better examples of "take-home messages"*

- RpoS is an alternative sigma factor that controls the expression of stress response genes in *Escherichia coli*. We looked at the conservation of the *rpoS* gene and found that it is present in $\gamma$-, $\beta$-, and $\delta$- proteobacteria.
  - Gives some context (more explanation of what sigma factors are would be helpful, depending on the intended audience), explains precisely what was discovered (the conservation of RpoS)
- All bacteria encounter oxidative stress, particularly pathogens targeted by immune cells. Glutathione is a major part of their defense against oxidative stress. We found that some pathogens, like *Mycobacterium tuberculosis*, do not have the genes for glutathione synthesis or reduction - instead, they use an alternative thiol, mycothiol.
  - Gives context and explains why the work is important (pathogens); explains precisely what the work adds to the field
</div>
</div>

## Identify the Content



Each section should be as concise as possible (ideally ≤ 100 words in most cases). Use bullet points instead of full sentences, but make sure that they convey your ideas clearly. 

Any text must conform to the norms of academic scientific communication – it must be precise, concise, and specific. (For example: “the LD50 of drug X is 50 $\mu$g/mL” is a clearer and better statement than “some toxicity was observed.”)

Use plenty of white space: large blocks of text are difficult for a reader to parse. 

### Title

- Should be short (ideally <15 words), very large font
- Should explain clearly what your research is about/what the major finding of your project is
- Does not need to be the same title as used for your written thesis. 
- Short, declarative statements or questions generally work well as poster titles


Use subheadings to divide your poster into different sections as appropriate for your project. These subheadings should be clear, concise, and informative: for example, “Cell division proteins in Archaea” is a better subheading than “Introduction.” The number and content of subsections may vary from one poster to another, but you must at a minimum include your aims and hypotheses, your work, and your conclusions.


<div id="goofus-gallant">
<div id="goofus">
*Bad examples of poster titles*
  
- **"The role of Cys188 in the function of YFP1 and mediating the protein-protein contacts between YFP1 and ABC6 in human epithelial cells exposed to EGF"**: lots of acronyms that the reader may not understand; too wordy; no context
- **"MAPKK and MAPKKK"**: acronyms that the reader may not understand; too vague
- **"AMR and the overprescription of co-amoxiclav, streptomycin, tetracycline, methicillin, and erythromycin"**; acronym that the reader may  not understand; long list of specialized terms the reader may not be familiar with
</div>

<div id="gallant">
*Good examples of poster titles*

- **"Do all bacteria have cell walls?"**: short and clear; asks a question to engage a reader's interest
- **"Identification of two genes essential for drought tolerance in *Arabidopsis*"**: short and to the point; makes the topic and main finding of the study clear
- **"Magnesium is an essential cofactor for the DNA polymerase from *Bacillus strathclydensis*"**: short declarative statement; makes the topic and main finding clear
</div>
</div>




## Conclusions and Significance

- 1-3 clear, concise "take home" messages for your audience
- Usually relating back to the aims/hypothesis defined earlier
- May use a model figure to summarize results/put results in context






## Slides as a tool for presenting content

- A short description of what the poster is about. May be a declarative statement of what the research has found, or a descriptive statement of what the research is about.   

However, a poster is not a manuscript, and you cannot simply copy/paste figures and text from your thesis onto a poster template. A poster is primarily about visual communication, so text should be kept at a minimum and figures should be kept simple and clear.


## Slide Titles

- Gives enough background for the reader to understand your research question and why it is important. 
- Clearly sets out the aims and hypothesis for the work

<div id="note">
The titles of the subsections on a poster may not match the sections listed above. For example, it is best to have clear, specific, focused titles that state the take-home message of a section (e.g., "Drug X decreases lymphocyte survival" instead of "Results").
</div>

## Slide Content


Slides that present experimental data:
- Gives enough information for the reader to understand how the experiments were done
  - Using a figure or flow diagram to illustrate the experimental design/principles behind the experiment can be very helpful
- Gives key parameters for the methods done, but not any extraneous details
- Include the data
  - Includes key results that answer the stated hypothesis/research aims
  - Uses figures or tablesthat illustrate the key points



